version: "3"

services:
  master:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:       
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      JAVA_OPTS: "-Duser.timezone=Europe/Kiev"
      JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
      JENKINS_OPTS: "--prefix="  
      SLAVE_IMAGE: "${SLAVE_IMAGE}:${SLAVE_TAG}"
      LOCAL: "true"
    volumes:
   #   - ./jenkins_home:/var/jenkins_home
   #   - ./seeddsl.groovy:/usr/share/jenkins/seeddsl.groovy 
   #   - ./config.xml:/usr/share/jenkins/seed-job-config.xml
      - ./casc_configs:/var/jenkins_home/casc_configs
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
      - ./plugins:/var/jenkins_home/plugins
   #   - ./init.groovy.d:/var/jenkins_home/init.groovy.d
   #   - ~/.ssh/id_rsa:/home/user/.ssh/id_rsa
